#!/bin/bash

#pkg install which
#pkg install wget

# Check for arguments
if [ -z "$1"  ]; then 
	echo "No server specified. Please enter server name. e.g. pkg-mason-install clangd"
	exit 1
fi

SERVER_NAME="$1"

echo "Checking if ${SERVER_NAME} is installed"

if [ $SERVER_NAME = "clangd" ]; then
	SERVER_NAME=$"clang"
fi

IS_INSTALLED=$(which "$SERVER_NAME")

if [ -z "$IS_INSTALLED" ]; then
	echo "${SERVER_NAME} is not installed. \n Installing..."
	#pkg update && pkg upgrade -y
	#pkg install $SERVER_NAME
fi
if [ $SERVER_NAME = "clang" ]; then
	SERVER_NAME=$"clangd"
fi

echo "$SERVER_NAME is installed"

SERVER_PATH=$(which "$SERVER_NAME")

if [ -z "$SERVER_PATH" ]; then
echo "Didn't find path to ${SERVER_NAME}."
#exit 1
fi

echo "$SERVER_NAME path: $SERVER_PATH"

MASON_DIR="~/.local/share/nvim/mason/packages/"$PACKAGE_NAME"/libexe"
if [ ! -d "MASON_DIR" ]; then
	echo "Mason directory not found. creating one..."
	mkdir -p "$MASON_DIR"
else
	echo "Path to mason packages $MASON_DIR"
fi

echo "Linking to mason path..."
ln -sf "$SERVER_PATH" "$MASON_DIR"/"$SERVER_NAME"

if [ -L "$MASON_DIR/libexe" ]; then
	echo "Symbolic link was succesfull"
else
	echo "ERROR: linking failed."
fi

echo "All done. Maybe it works maybe it wont."

